apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Patch the deployment.yaml to change container image in Daemonset
# to new tag on the image.
images:
  - name: quay.io/bpfman-userspace/go-kprobe-counter
    newName: quay.io/bpfman-userspace/go-kprobe-counter
    newTag: latest
# Patch the bytecode.yaml to change tag on the "url" field (which is an
# image) to new value. Since this is being done with an environment
# variable and using sed to replace, moved to patch.yaml.env which is
# converted to patch.yaml using the sed command in Makefile.
patches:
  - path: patch.yaml
    target:
      kind: KprobeProgram
      name: go-kprobe-counter-example
  - patch: |-
      - op: add
        path: "/metadata/labels"
        value: {"pod-security.kubernetes.io/enforce":"privileged","pod-security.kubernetes.io/warn":"privileged"}
    target:
      kind: Namespace
      name: go-kprobe-counter
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/securityContext/seLinuxOptions"
        value: {}
    target:
      kind: DaemonSet
      name: go-kprobe-counter-ds
  - patch: "- op: add\n  path: \"/spec/template/spec/containers/0/securityContext/seLinuxOptions/type\"\n  value: \n    bpfman-secure_go-kprobe-counter.process"
    target:
      kind: DaemonSet
      name: go-kprobe-counter-ds
resources:
  - selinux.yaml
  - binding.yaml
  - user-scc.yaml
  - ../../base/go-kprobe-counter
