apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Patch the bytecode.yaml to change tag on the "url" field (which is an
# image) to new value. Since this is being done with an environment
# variable and using sed to replace, moved to patch.yaml.env which is
# converted to patch.yaml using the sed command in Makefile.
patches:
- path: patch.yaml
  target:
    kind: XdpProgram
    name: go-xdp-counter-example
- patch: |-
    - op: add
      path: "/metadata/labels"
      value: {"pod-security.kubernetes.io/enforce":"privileged","pod-security.kubernetes.io/warn":"privileged"}
  target:
    kind: Namespace
    name: go-xdp-counter
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/securityContext/seLinuxOptions"
      value: {}
  target:
    kind: DaemonSet
    name: go-xdp-counter-ds
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/securityContext/seLinuxOptions/type"
      value:
        bpfman-secure-go-xdp-counter.process
  target:
    kind: DaemonSet
    name: go-xdp-counter-ds
resources:
- selinux.yaml
- binding.yaml
- ../../base/go-xdp-counter-sharing-map
images:
- name: quay.io/bpfman-userspace/go-xdp-counter
  newName: quay.io/bpfman-userspace/go-xdp-counter
  newTag: latest
