# .pre-commit-config.yaml
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yaml]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2-rules-docker
  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: cargo +nightly clippy
        args: [--all, --, --deny, warnings]
        language: system
        types: [rust]
        pass_filenames: false

      - id: fmt
        name: rustfmt
        entry: cargo +nightly fmt
        args: [--all, --, --check]
        language: system
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.18.5
    hooks:
      - id: cargo-deny
        args: [--all-features, check]

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.1
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        types: [go]
        language: golang
        pass_filenames: false
