[workspace]
members = ["bpfd", "bpfd-api", "bpfctl", "xtask", "tests/integration-test", "tests/integration-test-macros"]

[patch.crates-io]
aya = { git = "https://github.com/astoycos/aya", branch="map_pin" }
