site_name: bpfman
repo_url: https://github.com/bpfman/bpfman
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
site_dir: site

theme:
  name: material
  language: en
  logo: img/bpfman_icon.svg
  favicon: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Introduction: index.md
  - Getting Started:
      - Setup and Building: getting-started/building-bpfman.md
      - Run bpfman From Release Image: getting-started/running-release.md
      - Bpfman on Linux Tutorial: getting-started/tutorial.md
      - bpfctl Guide: getting-started/bpfctl-guide.md
      - Example eBPF Programs: getting-started/example-bpf.md
      - Deploying Example eBPF Programs On Local Host: getting-started/example-bpf-local.md
      - Deploying Example eBPF Programs On Kubernetes: getting-started/example-bpf-k8s.md
  - Developer Guide:
      - Contributing: governance/CONTRIBUTING.md
      - Reviewing Guide: governance/REVIEWING.md
      - Deploying the bpfman-operator: developer-guide/operator-quick-start.md
      - Developing the bpfman-operator: developer-guide/develop-operator.md
      - Kubernetes CRD API-Reference: developer-guide/api-spec.md
      - eBPF Bytecode Image Specifications: developer-guide/shipping-bytecode.md
      - bpfman Container Images: developer-guide/image-build.md
      - Documentation: developer-guide/documentation.md
      - Linux Capabilities: developer-guide/linux-capabilities.md
      - Logging: developer-guide/logging.md
      - Configuration: developer-guide/configuration.md
      - Testing: developer-guide/testing.md
      - Debugging: developer-guide/debugging.md
      - Releasing: developer-guide/release.md
  - Blog:
      - blog/index.md
  - Community:
      - Meetings: governance/MEETINGS.md
      - Governance: governance/GOVERNANCE.md
      - Code of Conduct: governance/CODE_OF_CONDUCT.md
      - Maintainers: governance/MAINTAINERS.md
      - Security: governance/SECURITY.md

plugins:
  - blog:
      # NOTE: configuration options can be found at
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
      blog_dir: blog
      blog_toc: true
      post_excerpt: required
      post_excerpt_max_authors: 2
  - search

copyright: Copyright &copy; 2021-2023 The bpfman contributors
