apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpfman-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfman-agent-role
subjects:
  - kind: ServiceAccount
    name: daemon
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-rolebinding
  namespace: bpfman
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bpfman-agent-role
subjects:
  - kind: ServiceAccount
    name: daemon
    namespace: system
