[package]
name = "bpfd-common"
version = "0.1.0"
edition = "2018"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", branch="main", optional=true }

[lib]
path = "src/lib.rs"