apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: bpfprogram-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-bpfprogram-editor-role
rules:
- apiGroups:
  - bpfd.dev
  resources:
  - bpfprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.dev
  resources:
  - bpfprograms/status
  verbs:
  - get
