---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Patch the bytecode.yaml to change tag on the "url" field (which is an
# image) to new value. This actually overwrites the image with the same value.
patches:
  - patch: |-
      - op: replace
        path: "/spec/bytecode/image/url"
        value: quay.io/bpfd-bytecode/go-tracepoint-counter:v0.3.1
    target:
      kind: TcProgram
      name: go-tracepoint-counter-example
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/securityContext/privileged"
        value: true
    target:
      kind: DaemonSet
      name: go-tracepoint-counter-ds
      namespace: go-tracepoint-counter
  - patch: |-
      - op: add
        path: "/metadata/labels"
        value: {"pod-security.kubernetes.io/enforce":"privileged","pod-security.kubernetes.io/audit":"privileged","pod-security.kubernetes.io/warn":"privileged"}
    target:
      kind: Namespace
      name: go-tracepoint-counter
# Patch the deployment.yaml to change container image in Daemonset
# to new tag on the image.
images:
  - name: quay.io/bpfd-userspace/go-tracepoint-counter
    newName: quay.io/bpfd-userspace/go-tracepoint-counter
    newTag: v0.3.1
resources: [../../base/go-tracepoint-counter, ocp-scc.yaml]
