apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: bpfman-secure
  namespace: go-uprobe-counter
spec:
  allow:
    '@self':
      bpf:
        - map_read
        - map_write
    'spc_t':
      bpf:
        - map_read
        - map_write
  inherit:
    - kind: System
      name: container
