---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: bpfprograms.bpfd.io
spec:
  group: bpfd.io
  names:
    kind: BpfProgram
    listKind: BpfProgramList
    plural: bpfprograms
    singular: bpfprogram
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BpfProgram is the Schema for the Bpfprograms API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BpfProgramSpec defines the desired state of BpfProgram
            properties:
              programs:
                additionalProperties:
                  description: BpfProgramMeta defines the relevant metadata needed
                    for a single running BpfProgram.
                  properties:
                    attachpoint:
                      description: AttachPoint specifies what this BpfProgram is attached
                        to for some programs is may be nil.
                      maxProperties: 1
                      minProperties: 1
                      properties:
                        networkmultiattach:
                          description: NetworkMultiAttach defines an attach point
                            for programs which attach to network devices and must
                            be ordered via bpfd.
                          properties:
                            direction:
                              default: NONE
                              description: Direction specifies the direction of traffic
                                the bpfprogram should attach to for a given network
                                device, this field should only be set for programs
                                of type TC. TODO(astoycos) see if kubebuilder can
                                handle more complicated validation for this.
                              enum:
                              - NONE
                              - INGRESS
                              - EGRESS
                              type: string
                            interface:
                              description: Interface refers to the name of a network
                                interface.
                              type: string
                            priority:
                              description: Priority specifies the priority of the
                                bpf program in relation to other programs of the same
                                type with the same attach point. It is a value from
                                0 to 1000 where lower values have higher precedence.
                              format: int32
                              maximum: 1000
                              minimum: 0
                              type: integer
                            proceedon:
                              description: 'ProceedOn allows the user to call other
                                programs in chain on this exit code. Multiple values
                                are supported by repeating the parameter. This feature
                                is only applicable for XDP programs. NOTE: These values
                                are not updatable following bpfProgramConfig creation.'
                              items:
                                enum:
                                - ABORTED
                                - DROP
                                - PASS
                                - TX
                                - REDIRECT
                                - DISPATCHER_RETURN
                                type: string
                              type: array
                          required:
                          - interface
                          - priority
                          type: object
                        singleattach:
                          description: SingleAttach defines an attach point for programs
                            which attach to a single entity and do not need to be
                            ordered.
                          properties:
                            name:
                              description: Name refers to the name of the attach point
                              type: string
                          required:
                          - name
                          type: object
                      type: object
                    maps:
                      additionalProperties:
                        type: string
                      description: 'Maps is a map with Keys: Map Names, and Values:
                        Map Pin paths'
                      type: object
                  required:
                  - maps
                  type: object
                description: 'ProgramMap is is a map with Keys: UUIDs, Values: BpfProgramMeta'
                type: object
            required:
            - programs
            type: object
          status:
            description: BpfProgramStatus defines the observed state of BpfProgram
              TODO Make these a fixed set of metav1.Condition.types and metav1.Condition.reasons
            properties:
              conditions:
                description: 'Conditions houses the updates regarding the actual implementation
                  of the bpf program on the node Known .status.conditions.type are:
                  "Available", "Progressing", and "Degraded"'
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a
                    foo's current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
