---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
