---
apiVersion: v1
kind: Namespace
metadata:
  name: go-uprobe-counter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpfman-app-go-uprobe-counter
  namespace: go-uprobe-counter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: go-uprobe-counter-ds
  namespace: go-uprobe-counter
  labels:
    k8s-app: go-uprobe-counter
spec:
  selector:
    matchLabels:
      name: go-uprobe-counter
  template:
    metadata:
      labels:
        name: go-uprobe-counter
    spec:
      nodeSelector: {}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: bpfman-app-go-uprobe-counter
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: go-uprobe-counter
          image: quay.io/bpfman-userspace/go-uprobe-counter:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: go-uprobe-counter-maps
              mountPath: /run/uprobe/maps
              readOnly: true
      volumes:
        - name: go-uprobe-counter-maps
          csi:
            driver: csi.bpfman.io
            volumeAttributes:
              csi.bpfman.io/program: go-uprobe-counter-example
              csi.bpfman.io/maps: uprobe_stats_map
