# permissions for end users to edit ebpfprograms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ebpfprogram-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/part-of: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
  name: ebpfprogram-editor-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - ebpfprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - ebpfprograms/status
  verbs:
  - get
