---
apiVersion: v1
kind: Namespace
metadata:
  name: go-xdp-counter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpfd-app-go-xdp-counter
  namespace: go-xdp-counter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-scc-xdp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: bpfd-app-go-xdp-counter
  namespace: go-xdp-counter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-xdp-counter
    app.kubernetes.io/part-of: go-xdp-counter
    app.kubernetes.io/managed-by: go-xdp-counter
  name: bpfd-app-rolebinding-go-xdp-counter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-bpfprogram-viewer-role
subjects:
- kind: ServiceAccount
  name: bpfd-app-go-xdp-counter
  namespace: go-xdp-counter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: go-xdp-counter-ds
  namespace: go-xdp-counter
  labels:
    k8s-app: go-xdp-counter
spec:
  selector:
    matchLabels:
      name: go-xdp-counter
  template:
    metadata:
      labels:
        name: go-xdp-counter
    spec:
      nodeSelector: {}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: bpfd-app-go-xdp-counter
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: go-xdp-counter
        image: quay.io/bpfd-userspace/go-xdp-counter:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: go-xdp-counter-maps
          mountPath: /run/bpfd/fs/maps
          readOnly: true
      volumes:
      - name: go-xdp-counter-maps
        hostPath:
          path: /run/bpfd/fs/maps
