apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kube-system
data:
  ## Can be configured at runtime
  bpfman.agent.image: quay.io/bpfman/bpfman-agent:latest
  bpfman.image: quay.io/bpfman/bpfman:latest
  ## Can be set to "info", "debug", or "trace"
  bpfman.agent.log.level: info
  ## See https://docs.rs/env_logger/latest/env_logger/ for configuration options
  bpfman.log.level: info
  bpfman.agent.healthprobe.addr: :8175
  bpfman.agent.metric.addr: 127.0.0.1:8174
  # Wait 5 minutes since cosign is slow, https://github.com/bpfman/bpfman/issues/1043
  bpfman.toml: |
    [database]
    max_retries = 30
    millisec_delay = 10000
