---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Patch the bytecode.yaml to change tag on the "url" field (which is an
# image) to new value. This actually overwrites the image with the same value.
patches:
  - target:
      kind: XdpProgram
      name: go-xdp-counter-sharing-map-example
    patch: |-
      - op: replace
        path: "/spec/bytecode/image/url"
        value: quay.io/bpfman-bytecode/go-xdp-counter:v0.4.2
# Patch the deployment.yaml to change container image in Daemonset
# to new tag on the image.
images:
  - name: quay.io/bpfman-userspace/go-xdp-counter
    newName: quay.io/bpfman-userspace/go-xdp-counter
    newTag: v0.4.2
resources: [../../selinux/go-xdp-counter-sharing-map]
