---
apiVersion: v1
kind: Namespace
metadata:
  name: go-tc-counter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpfd-app-go-tc-counter
  namespace: go-tc-counter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-scc-tc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: bpfd-app-go-tc-counter
    namespace: go-tc-counter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-tc-counter
    app.kubernetes.io/part-of: go-tc-counter
    app.kubernetes.io/managed-by: go-tc-counter
  name: bpfd-app-rolebinding-go-tc-counter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-bpfprogram-viewer-role
subjects:
  - kind: ServiceAccount
    name: bpfd-app-go-tc-counter
    namespace: go-tc-counter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: go-tc-counter-ds
  namespace: go-tc-counter
  labels:
    k8s-app: go-tc-counter
spec:
  selector:
    matchLabels:
      name: go-tc-counter
  template:
    metadata:
      labels:
        name: go-tc-counter
    spec:
      nodeSelector: {}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: bpfd-app-go-tc-counter
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: go-tc-counter
          image: quay.io/bpfd-userspace/go-tc-counter:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: go-tc-counter-maps
              mountPath: /run/tc/maps
              readOnly: true
      volumes:
        - name: go-tc-counter-maps
          csi:
            driver: csi.bpfd.dev
            volumeAttributes:
              csi.bpfd.dev/program: go-tc-counter-example
              csi.bpfd.dev/maps: tc_stats_map
