[interfaces]
[interfaces.eth0]
xdp_mode = "drv" # Valid xdp modes are "hw", "skb" and "drv". Default: "drv", but will fall back to "skb" on failure.

[signing]
allow_unsigned = true

[database]
max_retries = 10
millisec_delay = 1000
