name: bpfd-image-build

on:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/image-build.yaml' ]

env:
  REGISTRY: quay.io 
  REPOSITORY: bpfd 
  BPFD_IMAGE_NAME: bpfd
  BPFCTL_IMAGE_NAME: bpfctl
  BPFD_AGENT_IMAGE_NAME: bpfd-agent
  BPFD_OPERATOR_IMAGE_NAME: bpfd-operator

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    environment: image-repositories
    steps:
    - name: Check out rust source code
      uses: actions/checkout@v2

    - name: Login to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Extract metadata (tags, labels) for bpfd image
      id: meta-bpfd
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.BPFD_IMAGE_NAME }}

    - name: Build bpfd image
      id: build-bpfd
      uses: redhat-actions/buildah-build@v2
      with:
        image: bpfd
        tags: ${{ steps.meta-bpfd.outputs.tags }}
        labels: ${{ steps.meta-bpfd.outputs.labels }}
        containerfiles: |
          ./packaging/container-deployment/Containerfile.bpfd
    
    - name: Push bpfd to quay.io/bpfd
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-bpfd.outputs.image }}
        tags: ${{ steps.build-bpfd.outputs.tags }}
        registry: quay.io/bpfd

    - name: Extract metadata (tags, labels) for bpfctl image
      id: meta-bpfctl
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.BPFCTL_IMAGE_NAME }}

    - name: Build bpfctl image
      id: build-bpfctl
      uses: redhat-actions/buildah-build@v2
      with:
        image: bpfctl
        tags: ${{ steps.meta-bpfctl.outputs.tags }}
        labels: ${{ steps.meta-bpfctl.outputs.labels }}
        containerfiles: |
          ./packaging/container-deployment/Containerfile.bpfctl

    - name: Push bpfctl to quay.io/bpfd
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-bpfctl.outputs.image }}
        tags: ${{ steps.build-bpfctl.outputs.tags }}
        registry: quay.io/bpfd

    - name: Extract metadata (tags, labels) for bpfd-agent image
      id: meta-bpfd-agent
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.BPFD_AGENT_IMAGE_NAME }}

    - name: Build bpfd-agent image
      id: build-bpfd-agent
      uses: redhat-actions/buildah-build@v2
      with:
        image: bpfd-agent
        tags: ${{ steps. meta-bpfd-agent.outputs.tags }}
        labels: ${{ steps. meta-bpfd-agent.outputs.labels }}
        context: ./bpfd-operator
        containerfiles: |
          ./bpfd-operator/Containerfile.bpfd-agent

    - name: Push bpfd-agent to quay.io/bpfd
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-bpfd-agent.outputs.image }}
        tags: ${{ steps.build-bpfd-agent.outputs.tags }}
        registry: quay.io/bpfd
    
    - name: Extract metadata (tags, labels) for bpfd-operator image
      id: meta-bpfd-operator
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.BPFD_OPERATOR_IMAGE_NAME }}

    - name: Build bpfd-operator image
      id: build-bpfd-operator
      uses: redhat-actions/buildah-build@v2
      with:
        image: bpfd-operator
        tags: ${{ steps. meta-bpfd-operator.outputs.tags }}
        labels: ${{ steps. meta-bpfd-operator.outputs.labels }}
        context: ./bpfd-operator
        containerfiles: |
          ./bpfd-operator/Containerfile.bpfd-operator

    - name: Push bpfd-operator to quay.io/bpfd
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-bpfd-operator.outputs.image }}
        tags: ${{ steps.build-bpfd-operator.outputs.tags }}
        registry: quay.io/bpfd
        