apiVersion: bpfd.io/v1alpha1
kind: BpfProgramConfig
metadata:
  labels:
    app.kubernetes.io/name: BpfProgramConfig
  name: xdp-pass-all-nodes
spec:
  ## Must correspond to image section name
  name: pass
  type: XDP
  # Select all nodes
  nodeselector: {}
  attachpoint: 
    networkmultiattach: 
      interface: eth0
      priority: 0
  bytecode: image://quay.io/bpfd-bytecode/xdp_pass:latest
