apiVersion: bpfd.io/v1alpha1
kind: XdpProgram
metadata:
  labels:
    app.kubernetes.io/name: xdpprogram
  name: xdp-pass-all-nodes
spec:
  sectionname: pass
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    interface: eth0
  priority: 0
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/xdp_pass:latest
