apiVersion: bpfd.dev/v1alpha1
kind: TracepointProgram
metadata:
  labels:
    app.kubernetes.io/name: tracepointprogram
  name: tracepoint-example
spec:
  sectionname: hello
  # Select all nodes
  nodeselector: {}
  name: syscalls/sys_enter_openat
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/tracepoint:latest
