apiVersion: bpfd.io/v1alpha1
kind: BpfProgramConfig
metadata:
  labels:
    app.kubernetes.io/name: BpfProgramConfig
  name: go-counter-example
spec:
  ## Must correspond to image section name
  name: stats
  type: XDP
  # Select all nodes
  nodeselector:
    matchLabels: 
      deploy-ebpf: "true"
  attachpoint:
    networkmultiattach:
      interfaceselector:
        interface: eth0
      priority: 5
  bytecode:
    image:
      url: image://bpfd-bytecode/go-xdp-counter:latest