apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  namespace: kube-system
  labels:
    k8s-app: bpfd
spec:
  selector:
    matchLabels:
      name: bpfd-daemon
  template:
    metadata:
      labels:
        name: bpfd-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: bpfd-daemon
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: bpfd
        image: quay.io/bpfd/bpfd:latest
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        env: 
          - name: RUST_LOG
            valueFrom: 
              configMapKeyRef:
                name: bpfd-config
                key: bpfd.log.level
        volumeMounts:
        - name: runtime
          mountPath: /run/bpfd
          mountPropagation: Bidirectional
        - name: bpfd-ca
          mountPath: /etc/bpfd/certs/ca
          readOnly: true
        - name: bpfd-cert
          mountPath: /etc/bpfd/certs/bpfd
          readOnly: true
        - name: bpfd-config 
          mountPath: /etc/bpfd/bpfd.toml
          subPath: bpfd.toml
          readOnly: true
        # Mounted so bpfd doesn't try and create the client certificate
        - name: bpfd-agent-cert
          mountPath: /etc/bpfd/certs/bpfd-client
          readOnly: true
        - name: host-bytecode
          mountPath: /run/bpfd/bytecode
        # This mount is needed to attach tracepoint programs
        - name: host-debug
          mountPath: /sys/kernel/debug
        # Needed to ensure images are persisted to disk across restarts
        - name: bpfd-content-store
          mountPath: /var/lib/bpfd
          mountPropagation: Bidirectional
      - name: bpfd-agent 
        command:
        - /bpfd-agent      
        image: quay.io/bpfd/bpfd-agent:latest
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        env: 
          - name: NODENAME 
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GO_LOG
            valueFrom:
              configMapKeyRef:
                name: bpfd-config
                key: bpfd.log.level
        volumeMounts:
        - name: runtime
          mountPath: /run/bpfd
          mountPropagation: Bidirectional
        - name: bpfd-ca
          mountPath: /etc/bpfd/certs/ca
          readOnly: true
        - name: bpfd-agent-cert
          mountPath: /etc/bpfd/certs/bpfd-client
          readOnly: true
        - name: bpfd-config
          mountPath: /etc/bpfd/bpfd.toml
          subPath: bpfd.toml
          readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: runtime
        hostPath:
          path: /run/bpfd
      - name: bpfd-ca
        secret: 
          secretName: bpfd-ca
          optional: false
      - name: bpfd-cert
        secret:
          secretName: bpfd-cert-secret
          optional: false
      - name: bpfd-agent-cert
        secret:
          secretName: bpfd-agent-cert-secret
          optional: false
      - name: bpfd-config
        configMap:
          name: bpfd-config
          optional: false
      - name: host-bytecode
        hostPath:
          path: /run/bpfd/bytecode
      - name: host-debug
        hostPath:
          path: /sys/kernel/debug
      - name: bpfd-content-store
        hostPath:
          path: /var/lib/bpfd
